export const rarityData: any = {
  'ethereum-phunks': {
    Female: 3840,
    Earring: 2459,
    'Green Eye Shadow': 271,
    'Blonde Bob': 147,
    Male: 6039,
    Smile: 238,
    Mohawk: 441,
    'Wild Hair': 447,
    Pipe: 317,
    'Nerd Glasses': 572,
    Goat: 295,
    'Big Shades': 535,
    'Purple Eye Shadow': 262,
    'Half Shaved': 147,
    'Do-rag': 300,
    'Clown Eyes Blue': 384,
    Spots: 124,
    'Wild White Hair': 136,
    'Messy Hair': 460,
    'Luxurious Beard': 286,
    'Big Beard': 146,
    'Clown Nose': 212,
    'Police Cap': 203,
    'Blue Eye Shadow': 266,
    'Straight Hair Dark': 148,
    'Black Lipstick': 617,
    'Clown Eyes Green': 382,
    'Purple Lipstick': 655,
    'Blonde Short': 129,
    'Straight Hair Blonde': 144,
    'Pilot Helmet': 54,
    'Hot Lipstick': 696,
    'Regular Shades': 527,
    'Stringy Hair': 463,
    'Small Shades': 378,
    Frown: 261,
    'Eye Mask': 293,
    Muttonchops: 303,
    Bandana: 481,
    'Horned Rim Glasses': 535,
    'Crazy Hair': 414,
    'Classic Shades': 502,
    Handlebars: 263,
    'Mohawk Dark': 429,
    'Dark Hair': 157,
    'Peak Spike': 303,
    'Normal Beard Black': 289,
    Cap: 351,
    VR: 332,
    'Frumpy Hair': 442,
    Cigarette: 961,
    'Normal Beard': 292,
    'Red Mohawk': 147,
    'Shaved Head': 300,
    Chinstrap: 282,
    Mole: 644,
    'Knitted Cap': 419,
    Fedora: 186,
    'Shadow Beard': 526,
    'Straight Hair': 151,
    Hoodie: 259,
    'Eye Patch': 461,
    Headband: 406,
    'Cowboy Hat': 142,
    'Tassle Hat': 178,
    '3D Glasses': 286,
    Mustache: 288,
    Vape: 272,
    Choker: 48,
    'Pink With Hat': 95,
    'Welding Goggles': 86,
    'Vampire Hair': 147,
    'Mohawk Thin': 441,
    Tiara: 55,
    Zombie: 88,
    'Front Beard Dark': 260,
    'Cap Forward': 254,
    'Gold Chain': 169,
    'Purple Hair': 165,
    Beanie: 44,
    'Clown Hair Green': 148,
    Pigtails: 94,
    'Silver Chain': 156,
    'Front Beard': 273,
    'Rosy Cheeks': 128,
    'Orange Side': 68,
    'Wild Blonde': 144,
    'Buck Teeth': 78,
    'Top Hat': 115,
    'Medical Mask': 175,
    Ape: 24,
    Alien: 9,
  },
  'missing-phunks': {
    Alien: 12,
    Earring: 111,
    'Messy Hair': 14,
    'Gold Chain': 99,
    'Buck Teeth': 60,
    Headband: 26,
    'Purple Hair': 47,
    'Regular Shades': 26,
    Beanie: 20,
    Hoodie: 12,
    Fedora: 10,
    Smile: 27,
    'Big Beard': 22,
    'Top Hat': 15,
    Vr: 53,
    'Cowboy Hat': 33,
    '3d Glasses': 38,
    'Do-rag': 7,
    'Stringy Hair': 36,
    'Normal Beard': 13,
    'Clown Nose': 19,
    'Clown Hair Green': 26,
    'Shadow Beard': 33,
    Ape: 24,
    'Police Cap': 10,
    'Eye Patch': 14,
    'Luxurious Beard': 16,
    'Crazy Hair': 12,
    Bandana: 26,
    'Front Beard Dark': 10,
    'Eye Mask': 29,
    'Knitted Cap': 13,
    Mustache: 53,
    'Nerd Glasses': 4,
    'Front Beard': 5,
    Cap: 21,
    'Wild Hair': 9,
    'Big Shades': 7,
    Zombie: 36,
    Frown: 3,
    'Mohawk Dark': 1,
    'Cap Forward': 5,
    'Shaved Head': 9,
    'Normal Black Beard': 1,
    Muttonchops: 4,
    'Normal Beard Black': 6,
    'Mohawk Thin': 2,
    Handlebars: 10,
    'Vampire Hair': 2,
    Earrings: 1,
    Hnadlebars: 1,
    Male: 126,
    'Green Clown Hair': 1,
    Spots: 32,
    'Frond Beard Dark': 1,
    Mohawk: 2,
    Chinstrap: 6,
    'Clown Eyes Blue': 4,
    'Rosy Cheeks': 24,
    'Clown Eyes Green': 5,
    Mole: 1,
    Female: 51,
    'Orange Side': 10,
    'Black Lipstick': 9,
    'Wild Blonde': 4,
    Tiara: 9,
    'Purple Lipstick': 20,
    Pigtails: 7,
    'Pilot Helmet': 5,
    'Blue Eye Shadow': 4,
    'Straight Hair Blonde': 2,
    'Hot Lipstick': 19,
    'Purple Eye Shadow': 9,
    'Half Shaved': 5,
    'Green Eye Shadow': 6,
    'Pink With Hat': 2,
    Choker: 6,
    'Blonde Bob': 3,
    'Wild White Hair': 6,
    'Welding Goggles': 4,
    'Silver Chain': 4,
    'Wild Blonde Hair': 1,
    'Blonde Short': 1,
    'Dark Hair': 3,
    'Tassle Hat': 1,
  },
  'misprint-mingos': {
    Genesis: 1,
    'Backwards Cap Black': 145,
    'Long Sleeve White': 96,
    'Royal Red': 2,
    'Mingo Boba': 2,
    Test: 1,
    '3D Glasses': 95,
    Hoodie: 28,
    Gold: 118,
    'Mingo Barbie': 592,
    Hawaiian: 103,
    'Mingo Shrimp': 1597,
    'Puffy Coat Blue': 97,
    'Mingo Mollusk': 868,
    'Tie-Dye': 94,
    Gruff: 45,
    'Dojo Top': 26,
    'Backwards Cap White': 178,
    'Work Jacket': 41,
    'Mingo Gruff': 296,
    'French Navy Sweater': 85,
    'Backwards Cap Blue': 162,
    'Blocky Sweater': 28,
    'Lumberjack Flannel': 55,
    'Backwards Cap Red': 181,
    'Dress Shirt Pink': 65,
    'Puffy Coat Yellow': 46,
    'Moto Jacket Yellow': 83,
    'Baseball Cap Black': 122,
    'Dress Shirt Blue': 130,
    'Blue Flannel': 97,
    Moon: 25,
    Dojo: 15,
    Shaggy: 140,
    'Long Black': 160,
    'Long Blonde': 105,
    'Puffy Coat Orange': 66,
    'Solid Beard': 89,
    'Dress Shirt White': 131,
    Invisimingo: 139,
    'Mingo Crab': 162,
    'Epic Beard': 40,
    Spacesuit: 63,
    'FB Helmet Red': 14,
    'This Is Fine': 39,
    'Football - Megatron': 46,
    'Long Sleeve Deep V': 49,
    Cig: 106,
    'Breakdancer Elite': 60,
    Pajamas: 77,
    'Long Sleeve Grey': 37,
    'Long Sleeve V Blue': 37,
    Null: 133,
    'Knit Orange': 18,
    'Beak Gold': 36,
    'Flat Top': 75,
    'Satin Gold Jacket': 21,
    'Long Sleeve V Red': 72,
    'Camo Jacket': 57,
    'Long Sleeve V Aqua': 82,
    Robomingo: 19,
    'Varsity Purple': 41,
    'VR Red': 57,
    'Long Sleeve V Pink': 74,
    Tux: 25,
    'Backwards Cap Olive': 62,
    'Faux Shearling': 24,
    'Puffy Coat Green': 83,
    Black: 42,
    'Cool G Sweater': 18,
    'Tubesock - Lakers': 4,
    Superhero: 7,
    Noggles: 19,
    'Tubesock - Hawks': 21,
    'Puffy Coat Pink': 18,
    'Long Sleeve Natural': 46,
    'Pit Vipers': 6,
    'Breakdancer Blue': 82,
    'cc0 Sunset': 42,
    Frump: 47,
    'Long Pink': 20,
    Afro: 120,
    Bathrobe: 87,
    'Tennis Sweater': 40,
    Blue: 72,
    Salamander: 39,
    'Long Ginger': 40,
    'Mingoneck Aqua': 43,
    Toga: 26,
    'Gaming Headset': 124,
    Scribe: 17,
    'Nerd Glasses': 74,
    'Desert Camo': 43,
    'Ribbed Sweater': 43,
    'Breakdancer Double Red': 42,
    'Football - Bonk': 14,
    'VR Blue': 28,
    'Football - Duke': 31,
    'Football - Cheese Head': 24,
    'Moto Jacket Black': 50,
    'Breakdancer DMC': 15,
    'Vintage Track Jacket': 42,
    'Rainbow Vomit': 19,
    'Mingoneck White': 60,
    Stork: 5,
    Midnight: 2,
    'Puffy Coat Red': 70,
    'Havana Shades': 109,
    'Bucket Hat Purple': 15,
    'Space Helmet': 16,
    'Moto Jacket Red': 28,
    Pipe: 19,
    "Tubesock - 'Murica": 8,
    'Knit Royal': 35,
    'Jersey - Sammy D': 44,
    'Football - Kneel': 42,
    'Purp Nerd': 96,
    'Bucket Hat White': 35,
    Green: 17,
    'Varsity Blue': 57,
    'Football - Island': 33,
    'Long Sleeve Olive': 32,
    'Cobra Top': 21,
    'Bucket Hat Teal': 7,
    Scrubs: 23,
    Purps: 40,
    Ponytail: 36,
    'Faux Fur': 27,
    'Karen Cut': 35,
    'Bobsled Jacket': 23,
    'Tubesock - Cavaliers': 21,
    Purple: 19,
    'Knight Helmet': 10,
    'Shadow Beard': 45,
    Glitch_Bitch: 1,
    Checkered: 2,
    'Bill Jacket': 23,
    'Knit White': 11,
    'Football - Sheriff': 11,
    Red: 15,
    'Argyle Sweater': 38,
    'White Shag': 28,
    'Long Sleeve Pink': 11,
    'Varsity Burgundy': 31,
    'Dreads Short': 27,
    'Knight Armor': 3,
    'FB Helmet Green': 12,
    'Big Small Sweater': 7,
    'Mingoneck Black': 14,
    'Faux Diplomat': 25,
    'Hef Robe': 25,
    'Fancy Flannel': 21,
    'Knit Yellow': 12,
    'Breakdancer LL': 8,
    Cobra: 3,
    Havana: 50,
    'Baseball Cap White': 9,
    Cowboy: 1,
    'Varsity Green': 30,
    'Knit Purple': 23,
    Punk: 28,
    'Baseball Cap Navy': 14,
    'Dreads Long': 43,
    'Burrr Scarf': 1,
    Alligator: 7,
    'Racer Red': 4,
    'Lumberjack Hat': 13,
    Nerd: 38,
    Medallion: 3,
    'Backwards Cap Purple': 19,
    'FB Helmet Blue': 8,
    'Backwards Cap Fly': 2,
    'Eye Mask': 8,
    'Granddad Sweater': 19,
    'Classic Shades': 4,
    'BBall - Trust': 1,
    'Top Hat': 1,
    'Racer Orange': 8,
    'Racing Jacket': 7,
    'Life Vest': 4,
    Rude: 2,
    'Baseball Cap Purple': 7,
    'FB Helmet Olive': 3,
    'Safety Vest': 1,
    'FB Helmet Orange': 5,
    'Energy Dome 2004': 1,
    'BBall - Z': 2,
    'Coonskin Cap': 1,
    'Racer Yellow': 2,
    'VC Vest': 2,
    Lifesaver: 1,
    'LL Bucket': 2,
    'Wrestler Green': 1,
    'Royal Purple': 2,
    'Backwards Cap Leather': 2,
    Lava: 4,
    Win95: 3,
    'Spartan Helmet': 1,
    Heli: 4,
    Burrr: 2,
    'Jet Head': 2,
  },
  'dysto-phunks': {
    Alien: 5,
    'Cyber Brain': 2,
    Cyborg: 9,
    Hoodie: 7,
    'Cyber Eye': 7,
    'Shadow Synth Mask': 6,
    'Mohawk Green': 3,
    'Gas Mask': 5,
    'Short Mohawk': 2,
    'Green Scouter': 7,
    'Metal Green Mask': 4,
    'Thin Mohawk Green': 4,
    'Holo Lens': 2,
    Vape: 5,
    'Gold Chain': 9,
    Ape: 7,
    'Bionic Eye Patch': 4,
    'Shadow Hoodie': 2,
    'Cyclops Visor': 5,
    Cap: 2,
    'Wide Shades': 1,
    'Neon Gaze': 4,
    Bandana: 2,
    'Vortex Mask': 3,
    'Knitted Cap': 1,
    Zombie: 9,
    'Brain With Flies': 3,
    'Void Mask': 3,
    'Crazy Hair': 2,
    'Hyper Zoom Vr': 1,
    Earring: 14,
    'Peak Spike': 3,
    'Holo Black Mask': 3,
    'Meta Vr': 2,
    Robot: 6,
    'Neon Green Mask': 3,
    'Vr Headset': 2,
    'Police Cap': 1,
    'Vr Goggles': 1,
    Male: 24,
    'Brain Tube': 1,
    'Clown Hair White': 1,
    'Point Glasses': 1,
    'White Mustache': 1,
    'Green Cover': 2,
    Undercut: 1,
    'Cyber Matrix': 1,
    'Black Mask': 1,
    'Green Helmet': 2,
    'Wider Gaze': 1,
    'Green Alighment Mask': 1,
    'Flat Top Green': 1,
    'Cyber Sight': 1,
    'Black Cover': 1,
    'Void Goggles': 1,
    'Undead Mask': 1,
    'Infinity Shades Helmet': 1,
    'Invisible Helmet': 1,
    'Swamp Sight': 1,
    'Outlaw Mask': 2,
    'Eclipse Mask': 2,
    Pompadour: 1,
    'Black Hair': 1,
    'Futuristic Shades': 1,
    'Specter Shield Mask': 2,
    'Wild Green': 1,
    '3d Glasses': 1,
    'Wider Shades': 1,
    'Face Mask': 2,
    'Futuristic AR': 1,
    'Diamond Helmet': 1,
    'AR Shades': 2,
    'Short Black': 1,
    Philip: 1,
    'Cap Forward': 1,
    'Vr Goggles Flip': 1,
    PhunkBotV2: 1,
    'Cyber Residents': 2,
    Female: 19,
    'Pink Rose Hair': 1,
    'Exotic Black': 1,
    Tiara: 3,
    'Purple Line': 1,
    'Straight White': 1,
    'Pigtails White': 1,
    'Welding Googles': 1,
    'Wild Black': 1,
    'Afro Hair': 1,
    'Green Side': 2,
    'Straight Black Hair': 1,
    'Purple Bob': 1,
    'Black Shaved': 2,
    'Messy Green': 1,
    'Classic Shades': 2,
    'Wild White': 1,
    'Black Vr': 1,
  },
  'call-data-comrades': {
    '420': 61,
    Comrade: 9818,
    Commoner: 4011,
    'Sir Pinkalot': 2144,
    Corrupted: 1981,
    'Adeptus Cuborum': 1659,
    Psychonaut: 1197,
    Dexclesia: 1108,
    'Feeling Blue': 1098,
    'Upper Class': 1058,
    'Classic Punks BG': 1041,
    'In Dorkness We Trust': 1007,
    'Human Melanin Level 30': 977,
    'Human Melanin Level 80': 955,
    'Omega Block Zealots': 948,
    'Human Melanin Level Goth': 877,
    Scriboor: 867,
    'Pepe People': 732,
    'Purple People': 730,
    'Pork People': 721,
    'Public Servant': 689,
    'Perky Pork Pink': 688,
    'Blue People': 675,
    'Giga Green': 664,
    C3FF00: 626,
    'Alien People': 517,
    'Kombucha Mushroom People': 368,
    'Green Shirt': 351,
    Flannel: 346,
    'Black Shirt': 346,
    'Hardbass Uniform': 344,
    'Blue Shirt': 344,
    'Classic Black Suit': 340,
    'Deep Purple': 339,
    'Shady Lawyer Suit': 325,
    'Green Shirt Striped': 323,
    'Pink Shirt': 320,
    'McD Uniform': 309,
    'Block City Beach Resort (1337-Skulls)': 307,
    'Black Shirt Checkered': 304,
    'Purr People': 302,
    'Empty Stare': 300,
    'MEV Bot Protector Blue': 297,
    'Nerd Glasses': 296,
    'Classic Shades': 293,
    Wifebeater: 287,
    'White Shirt Stained': 284,
    'MEV Bot Protector Orange': 274,
    'Red Hoodie': 273,
    'Block City during Rollback(Chainrunners)': 269,
    'Perfectly Normal Eyes': 266,
    'Pink Shirt Striped': 261,
    'Jamaica Shirt': 261,
    'Black Ears': 260,
    'Bone People': 257,
    'Big Eyes': 255,
    'Mecha Crew Suit': 254,
    Seductive: 252,
    'Adeptus Cuborum Grunt Armor': 250,
    'BCPD Police Uniform': 243,
    'Black Hoodie': 235,
    'Yeti People': 228,
    'Simple Smile': 225,
    Satisfaction: 224,
    'Proud af': 223,
    'Insecure Laughter': 222,
    'Simple Ears For Simple People': 221,
    'Ready For Battle': 219,
    Bored: 217,
    'Visoor Blue': 217,
    'Perfectly Normal Mouth': 216,
    'Touching Grass (OnChainKevin)': 211,
    'Simple Simpleton Slit': 211,
    'Simple Frown': 209,
    'Irresistible Smile': 209,
    'For Real I Promise': 208,
    'TX Hash': 208,
    'Simple Indifference': 208,
    Aviators: 207,
    'Genesis Block Disciple': 206,
    'Four Stripes': 206,
    'Rad and Stripey': 205,
    'Sus af': 204,
    'Wide Awake': 203,
    'Block Visoor': 203,
    'Captains Uniform': 202,
    'Wink Wink': 202,
    'Mildly Surprising': 200,
    'Pussy Magnet': 199,
    'Quadrupel Block Speak': 199,
    'OY!!!!': 198,
    Goth: 198,
    'Trippin hard': 195,
    Paranoid: 195,
    'Evil Bot Visual Sensors': 195,
    'Blockchain Preacher': 194,
    'Useless Gills': 192,
    'Big Shades': 192,
    Brainiac: 191,
    'El Salvador': 191,
    'Highly Aesthetic Botox Lips': 189,
    'Mecha Crew Coms': 188,
    Matrix: 187,
    'Ghost Chain People': 187,
    'Purr Cheeks': 187,
    'Knights of the first Principles': 187,
    'Kombucha Mushroom People Exiled': 185,
    'Excellent Hearing': 185,
    'Adeptus Cuborum Gas Wars Veteran Armor': 185,
    'The Great Block in the Sky': 184,
    'Machine Elf Broadband Receiver': 184,
    'Presidential Suit': 182,
    'Seedphrase Mugger Mask': 182,
    Fleshy: 181,
    'Late Night Minting': 181,
    'Double Block Speak': 179,
    'The Blocks are Fine': 178,
    Blue: 178,
    'Ripping a Dart': 176,
    'Bone People Eyes': 174,
    'Visoor Pink': 172,
    'Lick it': 171,
    'Block Speak': 170,
    'Mecha Crew Goggles': 167,
    Horny: 167,
    'Block Space Block Space Block': 166,
    'Inner Sanctuary': 165,
    'OCK Nouns Glasses': 164,
    'Sunset over Block Assembly Complex C137': 163,
    'Pink Hoodie': 162,
    'Three Stripes': 161,
    'Official Rug Lord Fan Club Glasses': 161,
    'Bad Mood': 160,
    Stunned: 160,
    'Sunrise in Block City': 160,
    Pipe: 156,
    Cyclops: 155,
    'You Should See His..': 154,
    'Mohawk Dark': 152,
    'Mohawk Green': 152,
    Mohawk: 150,
    'Bandana Skull': 150,
    Floored: 149,
    'Block Vision Cyan Night': 149,
    'Block Speak (Drain Plains Pirates)': 147,
    'The Drain Plains': 146,
    'Brand New Gasmask': 144,
    Zombie: 143,
    'Nouns Glasses': 143,
    USA: 143,
    'Mecha Crew Pressure Stabilizer': 143,
    'Block Construction Crew Exosceleton': 142,
    'Quadrupel Block Vision': 142,
    'Ponytail Black': 142,
    Champ: 140,
    'The Freddy': 139,
    'Wild Purple Hair': 138,
    'Geriatric Rockabilly Sideburns': 136,
    'Sensual Lips': 136,
    'Unpleasent Residue': 135,
    'Ponytail Blonde': 135,
    'Geriatric Rockabilly': 134,
    'Mohawk Pink': 134,
    'Purple Cap': 132,
    'Three Day Stubble': 132,
    'Blockchain Maintanance Helmet': 131,
    'Adeptus Cuborum Helmet MKI': 131,
    Bandana: 130,
    'Angel Wings': 130,
    'McD Cap Black': 130,
    'Beard of the Gods': 128,
    Shaved: 127,
    'Mecha Crew Call Data Transceiver': 127,
    'Evil Bot Voice Modulator': 127,
    Smooth: 127,
    'Babby Hungry': 127,
    Antenna: 125,
    'Pork People Snout': 125,
    Ackchyually: 125,
    'Straight af': 123,
    'Ouch!': 122,
    'Pigtails Blonde': 122,
    'Most Simple Hair Blonde': 121,
    'Neck Tribal': 119,
    'Fancy Hair black': 119,
    'with a Pile of Shitcoins': 119,
    'Judge Judge': 116,
    'Eths Maxi Eyes': 115,
    ULULULULULUL: 115,
    'Pepe People Mouth': 115,
    'with a Trezor': 115,
    'watched by a Mischievous Floorbagorb': 114,
    'Prince Karen': 114,
    'Macs Noise': 114,
    'Mohawk White': 113,
    Edgelord: 113,
    'Alien Eyes': 112,
    'Knitted Cap': 112,
    'Pigtails brown': 109,
    'McD Cap Red': 109,
    'Adeptus Cuborum Block Tattoo': 109,
    'Fancy Hair blonde': 109,
    'Block Vision': 108,
    '3D Glasses': 107,
    'Eye Patch': 107,
    'Scarf of the Pruu Pruu People': 106,
    Headwind: 105,
    'AUX Flow': 104,
    'with a Ledger': 104,
    Emo: 102,
    'Sniffmaster 9000': 102,
    'Black Alpha Receiver': 101,
    'Ponytail Pink': 101,
    'Block Construction Forman Helmet': 100,
    'Lumberjack on Pipe Break': 100,
    'with a Moonbag': 100,
    'Punk Eyes': 99,
    'Most Simple Hair Red': 99,
    'Vampire Attack Attire': 98,
    'Pure Elegance': 97,
    'Orange Side Hair': 95,
    'Kinights Helmet': 94,
    'Gold Chain': 94,
    'Block Vision (Drain Plains Pirates)': 94,
    'Zoned out': 93,
    'Ego Death Ray': 93,
    'Bone People Mouth': 93,
    'BCPD Police Cap': 93,
    'General of the Adeptus Cuborum': 92,
    'Adeptus Cuborum Helmet MKIII': 92,
    'Bubble Tea Hair': 91,
    Slick: 90,
    'SKULLS FOR THE SKULL GOD': 90,
    'Ice Princess': 90,
    Lovebound: 88,
    'Auto GMer': 88,
    'Swimming Cap': 88,
    'Traditional Kaiju-Cow Hunter Camouflage': 87,
    'Double Block Vision': 86,
    Pruustafari: 86,
    'Punk Eyes Lady': 84,
    'ETH Tattoo': 84,
    'Genuine Unjaw': 84,
    'Ram Alamadingdong': 84,
    'Chewy 7700 Industrial': 84,
    'Single Use Doomsday Mask': 83,
    'Watching Titanic': 83,
    'Three Day Stubble with Tribal Tattoo': 83,
    'Hind Hair': 82,
    Vape: 82,
    'Chopper Hat': 81,
    'Iridescent Mantis Shrimpicorn Horn': 80,
    'Three Day Stubble with Block Tattoo': 78,
    'Amanita Muscaria Shower Cap': 77,
    'Floorbagorb Annihilator Jaw': 76,
    'Pit Vipers': 76,
    Gigantism: 75,
    'Wallet Drainer': 75,
    'Pretty Problematic Growth': 74,
    'Captains Hat': 74,
    'Wet Suit of the Grr People': 74,
    'He was never the same again': 73,
    'Please Replace Gasmask': 73,
    'Floored Ape Theory': 73,
    'Hash Mesh': 73,
    'Saudi People': 72,
    Abracadabrugged: 72,
    'Chewy 8800+': 70,
    'Ménage à neuf': 70,
    'Toxic Techno Granny': 70,
    'Purr People Snout': 69,
    'Blockthink Receiver': 68,
    'Death Cross Mask': 68,
    'Black and White Zombie': 68,
    'Weird Sexy Alien Lady': 68,
    'Swedish Lumberjack': 67,
    'Adeptus Cuborum Helmet MKIX': 66,
    'Ittybits Glasses': 66,
    'Three Day Stubble with ETH Tattoo': 66,
    'with a Golden Pigeon': 65,
    'Purr People Eyes': 64,
    'Gellar Field Projector': 64,
    'Purr People Mouse-Radar': 61,
    'Orange Lazer Dazer': 59,
    'Stunning Mouth Eye of the Hyppo Shamans': 59,
    'Who TF is making these Snorkles for Dogs': 59,
    'Circuit Hair': 59,
    'Golden Alpha Receiver': 59,
    'Scriboor Visoor': 58,
    'Dexclesia High Priest Armor': 57,
    'Logic Tree': 56,
    'Stuntman Helmet (PUNKAYC)-': 55,
    'Super Rare Holographic Ittybits Background': 54,
    'Gellar Shield': 54,
    'Fashion Hoodie': 54,
    'Trump Hair': 53,
    'Drain Lord Martha Focker Mask': 53,
    'Tippy Toppy Top Hat': 53,
    'Super Sick Cap': 52,
    'Sinful Halo': 51,
    'Maga Cap': 50,
    Impossimouth: 50,
    'We the people': 50,
    'Legends of Block City': 47,
    'Beak of the Pruu Pruu People': 45,
    'with a Green Lambo': 44,
    'Carbon Fibre Sideburns': 43,
    'Vomit Tier 1 Call The Doctor!': 43,
    'Honorary Citizen': 43,
    Ethernals: 42,
    'Floorbagorb Annihilator Goggles': 42,
    'Green Phazer Bobazer': 42,
    'with an Orange Lambo': 42,
    'Block Vision ETHS Heart': 41,
    'SkullX Raiders Visoor': 41,
    'Imaginary Scriptoadz Companion': 41,
    Bubblegum: 35,
    'Chewy 9000 Connoisseur Edition': 35,
    Geylo: 35,
    'Dragon Mask of the Pamp People': 34,
    'Horns of the Peeperz People': 33,
    'Nam June PIV (PIVproved)': 31,
    'Floorbagorb Annihilator Jaw (activated)': 31,
    'Golden Hoodie': 30,
    'Golden Crown': 28,
    'Vomit Tier 2 Call the Gender Studies Teacher!!': 27,
    'Golden Gas Mask': 26,
    'Block Explorer of the Dexclesia': 24,
    'Vitaliks Blessing': 24,
    'Candle of Despair': 22,
    'Pure Eths Crystal': 20,
    'Comrade of Nyan': 20,
    'Floorbagorb Annihilator Goggles (activated)': 18,
    'Candle of Frolic': 17,
    'Holy Forking Staff': 17,
    'Vomit Tier 3 CALL THE UNICORNS!!!': 15,
    'Sword of Consensus': 14,
    'Scepter of Immutability': 14,
    'Nyan Goggles': 12,
    Passes: 12,
    Golden: 9,
    'Vomit Tier 4 CaLL tHe GoDS!!!!': 4,
    Jazz: 3,
    'Matrix Animated': 3,
    'Rainbow Mayhem': 3,
    Lava: 2,
    '10Honk': 1,
    AUXVI: 1,
    Afterparty: 1,
    Ariana: 1,
    BattleBudiez: 1,
    BobbyZoo: 1,
    Chopper: 1,
    Chris: 1,
    Cryptoferd: 1,
    Darknezz: 1,
    Dave: 1,
    Dragic: 1,
    Hirsch: 1,
    'Jack Shepherd': 1,
    Jeremy: 1,
    King: 1,
    Knox: 1,
    MEK: 1,
    Macs: 1,
    MadYak: 1,
    Maning: 1,
    McHexley: 1,
    McHexley2: 1,
    Middlemarch: 1,
    'NML Anon01': 1,
    'NML Anon02': 1,
    NVMD: 1,
    Notaz: 1,
    PRGuitarman: 1,
    PivPiv: 1,
    Prorok: 1,
    Reidnol: 1,
    Sartoshi: 1,
    'Scarce Punk': 1,
    Scribble: 1,
    Sneps: 1,
    TheStakerClass: 1,
    'Vaccine the $PAMP Kaiser': 1,
    'Virtual Alaska': 1,
    Web3DMD: 1,
    Wusgood: 1,
    Xcopy: 1,
    Yonder_McHexley: 1,
    'A Wild Gas Guzzler Appears': 1,
    'Babby Comrade': 1,
    'Block Contruction Crew Foreman': 1,
    'Block Pepe': 1,
    'Conversing with Machine Elves': 1,
    'Crying Comrade': 1,
    'Default Comrade 0815': 1,
    'Default Comrade 0816': 1,
    Dickbutt: 1,
    'Donald J': 1,
    'Dumb Contract': 1,
    'Ethernal Prime': 1,
    'Genesis Block': 1,
    'High af at the Beach': 1,
    'Imposter Captain at the Beach Resort': 1,
    'Licker Block': 1,
    'Lonely Golden Boy': 1,
    'MEV Bot': 1,
    'MSPAINT Comrade': 1,
    'Mecha Corps General (Adeptus Cuborum)': 1,
    'Mecha Corps General (Hordes of the Rug Lord)': 1,
    'Mecha Pilot (Adeptus Cuborum)': 1,
    'Mecha Pilot (Hordes of the Rug Lord)': 1,
    'Pirate King of the Drain Plains': 1,
    'Purr People Pure Breed': 1,
    'Ranting Shitfluencer': 1,
    'Reorg Attack Victim of Block 3,887,075 (colorized)': 1,
    'Smart Contract': 1,
    'Sunrise over Block City Cityscape, framed': 1,
    'Sunset over Block Assembly Complex C137, framed': 1,
    'Techno Lord XIX': 1,
    'Techno Lord XX': 1,
    'Techno Lord XXI': 1,
    'Techno Lord XXII': 1,
    'Techno Lord XXIII': 1,
    'Techno Lord XXIV': 1,
    'The Drain Plains, framed': 1,
    'The First Wei': 1,
    'The Four Henchmen, 99 Percent Attack': 1,
    'The Four Henchmen, Alien Invasion': 1,
    'The Four Henchmen, Singularity': 1,
    'The Four Henchmen, Zombie Ablockalypse': 1,
    'The Holesome Man': 1,
    'The Omega Block': 1,
    'The Rug Lord': 1,
    'Validator Rex in full Gas Wars Armor': 1,
    'Gold Pass 1': 1,
    'Gold Pass 2': 1,
    'Gold Pass 3': 1,
    'Silver Pass 1': 1,
    'Silver Pass 2': 1,
    'Silver Pass 3': 1,
    'Silver Pass 4': 1,
    'Silver Pass 5': 1,
    'Silver Pass 6': 1,
    'Silver Pass 7': 1,
    'Silver Pass 8': 1,
    'Silver Pass 9': 1,
  },
};

export const ignoredTraitFilters: { [key: string]: string[] } = {
  'ethereum-phunks': [],
  'missing-phunks': [],
  'misprint-mingos': [],
  'dysto-phunks': [],
  'call-data-comrades': ['Description', 'Name'],
};

export const ignoredTraitFiltersForCounts: { [key: string]: string[] } = {
  'ethereum-phunks': ['Sex'],
  'missing-phunks': ['Sex'],
  'misprint-mingos': [],
  'dysto-phunks': ['Sex'],
  'call-data-comrades': ['Description', 'Name'],
};
