export const traits: any = {
  'ethereum-phunks': {
    Female: 3840,
    Earring: 2459,
    'Green Eye Shadow': 271,
    'Blonde Bob': 147,
    Male: 6039,
    Smile: 238,
    Mohawk: 441,
    'Wild Hair': 447,
    Pipe: 317,
    'Nerd Glasses': 572,
    Goat: 295,
    'Big Shades': 535,
    'Purple Eye Shadow': 262,
    'Half Shaved': 147,
    'Do-rag': 300,
    'Clown Eyes Blue': 384,
    Spots: 124,
    'Wild White Hair': 136,
    'Messy Hair': 460,
    'Luxurious Beard': 286,
    'Big Beard': 146,
    'Clown Nose': 212,
    'Police Cap': 203,
    'Blue Eye Shadow': 266,
    'Straight Hair Dark': 148,
    'Black Lipstick': 617,
    'Clown Eyes Green': 382,
    'Purple Lipstick': 655,
    'Blonde Short': 129,
    'Straight Hair Blonde': 144,
    'Pilot Helmet': 54,
    'Hot Lipstick': 696,
    'Regular Shades': 527,
    'Stringy Hair': 463,
    'Small Shades': 378,
    Frown: 261,
    'Eye Mask': 293,
    Muttonchops: 303,
    Bandana: 481,
    'Horned Rim Glasses': 535,
    'Crazy Hair': 414,
    'Classic Shades': 502,
    Handlebars: 263,
    'Mohawk Dark': 429,
    'Dark Hair': 157,
    'Peak Spike': 303,
    'Normal Beard Black': 289,
    Cap: 351,
    VR: 332,
    'Frumpy Hair': 442,
    Cigarette: 961,
    'Normal Beard': 292,
    'Red Mohawk': 147,
    'Shaved Head': 300,
    Chinstrap: 282,
    Mole: 644,
    'Knitted Cap': 419,
    Fedora: 186,
    'Shadow Beard': 526,
    'Straight Hair': 151,
    Hoodie: 259,
    'Eye Patch': 461,
    Headband: 406,
    'Cowboy Hat': 142,
    'Tassle Hat': 178,
    '3D Glasses': 286,
    Mustache: 288,
    Vape: 272,
    Choker: 48,
    'Pink With Hat': 95,
    'Welding Goggles': 86,
    'Vampire Hair': 147,
    'Mohawk Thin': 441,
    Tiara: 55,
    Zombie: 88,
    'Front Beard Dark': 260,
    'Cap Forward': 254,
    'Gold Chain': 169,
    'Purple Hair': 165,
    Beanie: 44,
    'Clown Hair Green': 148,
    Pigtails: 94,
    'Silver Chain': 156,
    'Front Beard': 273,
    'Rosy Cheeks': 128,
    'Orange Side': 68,
    'Wild Blonde': 144,
    'Buck Teeth': 78,
    'Top Hat': 115,
    'Medical Mask': 175,
    Ape: 24,
    Alien: 9,
  },
  'missing-phunks': {
    Alien: 12,
    Earring: 111,
    'Messy Hair': 14,
    'Gold Chain': 99,
    'Buck Teeth': 60,
    Headband: 26,
    'Purple Hair': 47,
    'Regular Shades': 26,
    Beanie: 20,
    Hoodie: 12,
    Fedora: 10,
    Smile: 27,
    'Big Beard': 22,
    'Top Hat': 15,
    Vr: 53,
    'Cowboy Hat': 33,
    '3d Glasses': 38,
    'Do-rag': 7,
    'Stringy Hair': 36,
    'Normal Beard': 13,
    'Clown Nose': 19,
    'Clown Hair Green': 26,
    'Shadow Beard': 33,
    Ape: 24,
    'Police Cap': 10,
    'Eye Patch': 14,
    'Luxurious Beard': 16,
    'Crazy Hair': 12,
    Bandana: 26,
    'Front Beard Dark': 10,
    'Eye Mask': 29,
    'Knitted Cap': 13,
    Mustache: 53,
    'Nerd Glasses': 4,
    'Front Beard': 5,
    Cap: 21,
    'Wild Hair': 9,
    'Big Shades': 7,
    Zombie: 36,
    Frown: 3,
    'Mohawk Dark': 1,
    'Cap Forward': 5,
    'Shaved Head': 9,
    'Normal Black Beard': 1,
    Muttonchops: 4,
    'Normal Beard Black': 6,
    'Mohawk Thin': 2,
    Handlebars: 10,
    'Vampire Hair': 2,
    Earrings: 1,
    Hnadlebars: 1,
    Male: 126,
    'Green Clown Hair': 1,
    Spots: 32,
    'Frond Beard Dark': 1,
    Mohawk: 2,
    Chinstrap: 6,
    'Clown Eyes Blue': 4,
    'Rosy Cheeks': 24,
    'Clown Eyes Green': 5,
    Mole: 1,
    Female: 51,
    'Orange Side': 10,
    'Black Lipstick': 9,
    'Wild Blonde': 4,
    Tiara: 9,
    'Purple Lipstick': 20,
    Pigtails: 7,
    'Pilot Helmet': 5,
    'Blue Eye Shadow': 4,
    'Straight Hair Blonde': 2,
    'Hot Lipstick': 19,
    'Purple Eye Shadow': 9,
    'Half Shaved': 5,
    'Green Eye Shadow': 6,
    'Pink With Hat': 2,
    Choker: 6,
    'Blonde Bob': 3,
    'Wild White Hair': 6,
    'Welding Goggles': 4,
    'Silver Chain': 4,
    'Wild Blonde Hair': 1,
    'Blonde Short': 1,
    'Dark Hair': 3,
    'Tassle Hat': 1,
  },
  'missing-punks': {
    Alien: 12,
    Earring: 110,
    'Messy Hair': 14,
    'Gold Chain': 99,
    'Buck Teeth': 60,
    Headband: 26,
    'Purple Hair': 47,
    'Regular Shades': 26,
    Beanie: 20,
    Hoodie: 12,
    Fedora: 10,
    Smile: 27,
    'Big Beard': 22,
    'Top Hat': 15,
    Vr: 54,
    'Cowboy Hat': 33,
    '3d Glasses': 38,
    'Do-rag': 7,
    'Stringy Hair': 36,
    'Normal Beard': 13,
    'Clown Nose': 19,
    'Clown Hair Green': 26,
    'Shadow Beard': 33,
    Ape: 24,
    'Police Cap': 11,
    'Eye Patch': 15,
    'Luxurious Beard': 16,
    'Crazy Hair': 12,
    Bandana: 26,
    'Front Beard Dark': 10,
    'Eye Mask': 29,
    'Knitted Cap': 14,
    Mustache: 53,
    'Nerd Glasses': 4,
    'Front Beard': 5,
    Cap: 21,
    'Wild Hair': 9,
    'Big Shades': 7,
    Zombie: 36,
    Frown: 3,
    'Mohawk Dark': 1,
    'Cap Forward': 4,
    'Shaved Head': 8,
    'Normal Black Beard': 1,
    Muttonchops: 4,
    'Normal Beard Black': 6,
    'Mohawk Thin': 2,
    Handlebars: 10,
    'Vampire Hair': 2,
    Earrings: 1,
    Hnadlebars: 1,
    Male: 126,
    'Green Clown Hair': 1,
    Spots: 32,
    'Frond Beard Dark': 1,
    Mohawk: 2,
    Chinstrap: 6,
    'Clown Eyes Blue': 4,
    'Rosy Cheeks': 24,
    'Clown Eyes Green': 5,
    Mole: 1,
    Female: 52,
    'Orange Side': 10,
    'Black Lipstick': 9,
    'Wild Blonde': 4,
    Tiara: 9,
    'Purple Lipstick': 20,
    Pigtails: 7,
    'Pilot Helmet': 5,
    'Blue Eye Shadow': 4,
    'Straight Hair Blonde': 2,
    'Hot Lipstick': 20,
    'Purple Eye Shadow': 10,
    'Half Shaved': 5,
    'Green Eye Shadow': 6,
    'Pink With Hat': 2,
    Choker: 6,
    'Blonde Bob': 4,
    'Wild White Hair': 6,
    'Welding Goggles': 4,
    'Silver Chain': 4,
    'Wild Blonde Hair': 1,
    'Blonde Short': 1,
    'Dark Hair': 3,
    'Tassle Hat': 1,
  },
};
